version: "3.2"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
